namespace :seed do
  desc "Populate participations"
  task second_friday_participations: :environment do 
    Participation.create!([
    #December 2016
      {event_id: 11, gallery_id: 11},
      {event_id: 11, gallery_id: 14},
      {event_id: 11, gallery_id: 15},
      {event_id: 11, gallery_id: 17},
      {event_id: 11, gallery_id: 19},
      {event_id: 11, gallery_id: 22},
      {event_id: 11, gallery_id: 29},
      {event_id: 11, gallery_id: 30},
      {event_id: 11, gallery_id: 32},
      {event_id: 11, gallery_id: 34},
      {event_id: 11, gallery_id: 36},
    #January 2017
      {event_id: 10, gallery_id: 11},
      {event_id: 10, gallery_id: 14},
      {event_id: 10, gallery_id: 15},
      {event_id: 10, gallery_id: 21},
      {event_id: 10, gallery_id: 25},
      {event_id: 10, gallery_id: 26},
      {event_id: 10, gallery_id: 27},
      {event_id: 10, gallery_id: 29},
      {event_id: 10, gallery_id: 32},
      {event_id: 10, gallery_id: 34},
      {event_id: 10, gallery_id: 36},
    #February 2017
      {event_id: 9, gallery_id: 11},
      {event_id: 9, gallery_id: 14},
      {event_id: 9, gallery_id: 15},
      {event_id: 9, gallery_id: 22},
      {event_id: 9, gallery_id: 23},
      {event_id: 9, gallery_id: 25},
      {event_id: 9, gallery_id: 26},
      {event_id: 9, gallery_id: 27},
      {event_id: 9, gallery_id: 32},
      {event_id: 9, gallery_id: 36},
    #March 2017
      {event_id: 8, gallery_id: 11},
      {event_id: 8, gallery_id: 12},
      {event_id: 8, gallery_id: 14},
      {event_id: 8, gallery_id: 15},
      {event_id: 8, gallery_id: 17},
      {event_id: 8, gallery_id: 19},
      {event_id: 8, gallery_id: 21},
      {event_id: 8, gallery_id: 22},
      {event_id: 8, gallery_id: 25},
      {event_id: 8, gallery_id: 26},
      {event_id: 8, gallery_id: 27},
      {event_id: 8, gallery_id: 28},
      {event_id: 8, gallery_id: 31},
      {event_id: 8, gallery_id: 32},
      {event_id: 8, gallery_id: 34},
      {event_id: 8, gallery_id: 36},
      {event_id: 8, gallery_id: 40},
    #April 2017
      {event_id: 7, gallery_id: 11},
      {event_id: 7, gallery_id: 12},
      {event_id: 7, gallery_id: 14},
      {event_id: 7, gallery_id: 15},
      {event_id: 7, gallery_id: 17},
      {event_id: 7, gallery_id: 22},
      {event_id: 7, gallery_id: 25},
      {event_id: 7, gallery_id: 26},
      {event_id: 7, gallery_id: 27},
      {event_id: 7, gallery_id: 29},
      {event_id: 7, gallery_id: 32},
      {event_id: 7, gallery_id: 34},
      {event_id: 7, gallery_id: 36},
      {event_id: 7, gallery_id: 40},
      {event_id: 7, gallery_id: 41},
    #May 2017
      {event_id: 6, gallery_id: 12},
      {event_id: 6, gallery_id: 15},
      {event_id: 6, gallery_id: 17},
      {event_id: 6, gallery_id: 19},
      {event_id: 6, gallery_id: 22},
      {event_id: 6, gallery_id: 26},
      {event_id: 6, gallery_id: 27},
      {event_id: 6, gallery_id: 28},
      {event_id: 6, gallery_id: 29},
      {event_id: 6, gallery_id: 36},
    #June 2017
      {event_id: 5, gallery_id: 11},
      {event_id: 5, gallery_id: 12},
      {event_id: 5, gallery_id: 15},
      {event_id: 5, gallery_id: 17},
      {event_id: 5, gallery_id: 19},
      {event_id: 5, gallery_id: 25},
      {event_id: 5, gallery_id: 26},
      {event_id: 5, gallery_id: 27},
      {event_id: 5, gallery_id: 29},
      {event_id: 5, gallery_id: 30},
      {event_id: 5, gallery_id: 36},
      {event_id: 5, gallery_id: 39},
      {event_id: 5, gallery_id: 40},
    #July 2017
      {event_id: 4, gallery_id: 12},
      {event_id: 4, gallery_id: 15},
      {event_id: 4, gallery_id: 17},
      {event_id: 4, gallery_id: 19},
      {event_id: 4, gallery_id: 21},
      {event_id: 4, gallery_id: 22},
      {event_id: 4, gallery_id: 26},
      {event_id: 4, gallery_id: 27},
      {event_id: 4, gallery_id: 29},
      {event_id: 4, gallery_id: 30},
      {event_id: 4, gallery_id: 32},
      {event_id: 4, gallery_id: 36},
      {event_id: 4, gallery_id: 39},
      {event_id: 4, gallery_id: 40},
      {event_id: 4, gallery_id: 41},
      {event_id: 4, gallery_id: 42},
    #August 2017
      {event_id: 3, gallery_id: 11},
      {event_id: 3, gallery_id: 15},
      {event_id: 3, gallery_id: 17},
      {event_id: 3, gallery_id: 19},
      {event_id: 3, gallery_id: 21},
      {event_id: 3, gallery_id: 25},
      {event_id: 3, gallery_id: 26},
      {event_id: 3, gallery_id: 27},
      {event_id: 3, gallery_id: 28},
      {event_id: 3, gallery_id: 29},
      {event_id: 3, gallery_id: 30},
      {event_id: 3, gallery_id: 32},
      {event_id: 3, gallery_id: 36},
      {event_id: 3, gallery_id: 41},
      {event_id: 3, gallery_id: 42},
    #September 2017
      {event_id: 2, gallery_id: 30},
      {event_id: 2, gallery_id: 21},
      {event_id: 2, gallery_id: 42},
      {event_id: 2, gallery_id: 27},
      {event_id: 2, gallery_id: 44},
      {event_id: 2, gallery_id: 36},
      {event_id: 2, gallery_id: 41},
      {event_id: 2, gallery_id: 22},
      {event_id: 2, gallery_id: 29},
      {event_id: 2, gallery_id: 32},
      {event_id: 2, gallery_id: 25},
      {event_id: 2, gallery_id: 12},
      {event_id: 2, gallery_id: 15},
    #October 2017
      {event_id: 1, gallery_id: 22},
      {event_id: 1, gallery_id: 27},
      {event_id: 1, gallery_id: 29},
    ])
  end
end